spring:
  profiles:
    active: local  # 기본 프로파일을 local로 설정
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update # prod에서는 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT 설정 (모든 환경 공통)
jwt:
  secret: ${JWT_SECRET_KEY}

---
# Local 환경 설정
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

---
# Dev 환경 설정  
spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://dev-server.com/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

---
# Prod 환경 설정
spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: https://prod-server.com/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email